### PR TITLE
add scripts, make pypi compatible

### PR DESCRIPTION
**Pull request by blackmad**
https://pypi.python.org/pypi/scala-source-tools/0.11

### CODE REVIEW

**Comment by blackmad** [comment]
comments addressed, new diff pushed.

uploading to pypi warns about not having a README in the directory but it's fine.

**Comment by benjyw** [comment]
Github is so janky. If I merge will it merge in all the commits, or will it squash them?

**Comment by benjyw** [comment]
Also:  https://github.com/foursquare/source_code_analysis/tree/tmp_branch_for_dblackman

I just dropped the files in there. You'll probably need to massage them to get them to do anything.

**Comment by blackmad** [comment]
I think I need to squash, push a new branch and make a new merge request.
Can do

**Comment by blackmad** [comment]
okay, I squashed everything. can you merge?

**Comment by benjyw** [comment]
Done.

**Pull request merged**
